<?php

// This is a compiled Agavi configuration file
// Compiled from: C:/ws/tabeshtour/app/modules/Admin/config/autoload.xml
// Generated by: AgaviAutoloadConfigHandler
// Date: 2013-06-29T17:44:43+0000

return array (
  'agentAdminBaseAction' => 'C:\\ws\\tabeshtour\\app/modules/Admin/lib/action/agentAdminBaseAction.class.php',
  'agentAdminBaseModel' => 'C:\\ws\\tabeshtour\\app/modules/Admin/lib/model/agentAdminBaseModel.class.php',
  'agentAdminBaseView' => 'C:\\ws\\tabeshtour\\app/modules/Admin/lib/view/agentAdminBaseView.class.php',
);

?>