<?php

// This is a compiled Agavi configuration file
// Compiled from: C:/ws/agent/app/modules/Admin/config/autoload.xml
// Generated by: AgaviAutoloadConfigHandler
// Date: 2013-06-26T22:08:40+0000

return array (
  'agentAdminBaseAction' => 'C:\\ws\\agent\\app/modules/Admin/lib/action/agentAdminBaseAction.class.php',
  'agentAdminBaseModel' => 'C:\\ws\\agent\\app/modules/Admin/lib/model/agentAdminBaseModel.class.php',
  'agentAdminBaseView' => 'C:\\ws\\agent\\app/modules/Admin/lib/view/agentAdminBaseView.class.php',
);

?>