<?php

// This is a compiled Agavi configuration file
// Compiled from: C:/ws/tabeshtour/app/modules/Default/config/autoload.xml
// Generated by: AgaviAutoloadConfigHandler
// Date: 2013-06-27T02:13:28+0000

return array (
  'agentDefaultBaseAction' => 'C:\\ws\\tabeshtour\\app/modules/Default/lib/action/agentDefaultBaseAction.class.php',
  'agentDefaultBaseModel' => 'C:\\ws\\tabeshtour\\app/modules/Default/lib/model/agentDefaultBaseModel.class.php',
  'agentDefaultBaseView' => 'C:\\ws\\tabeshtour\\app/modules/Default/lib/view/agentDefaultBaseView.class.php',
);

?>