<?php

// This is a compiled Agavi configuration file
// Compiled from: C:/ws/tabeshtour/app/modules/Widgets/config/autoload.xml
// Generated by: AgaviAutoloadConfigHandler
// Date: 2013-06-27T02:13:28+0000

return array (
  'agentWidgetsBaseAction' => 'C:\\ws\\tabeshtour\\app/modules/Widgets/lib/action/agentWidgetsBaseAction.class.php',
  'agentWidgetsBaseModel' => 'C:\\ws\\tabeshtour\\app/modules/Widgets/lib/model/agentWidgetsBaseModel.class.php',
  'agentWidgetsBaseView' => 'C:\\ws\\tabeshtour\\app/modules/Widgets/lib/view/agentWidgetsBaseView.class.php',
);

?>