<?php

// This is a compiled Agavi configuration file
// Compiled from: C:/ws/agent/app/config/compile.xml
// Generated by: AgaviCompileConfigHandler
// Date: 2013-06-26T22:08:40+0000

require('C:\\ws\\agent\\libs\\agavi\\util\\AgaviAttributeHolder.class.php');
require('C:\\ws\\agent\\libs\\agavi\\action\\AgaviAction.class.php');
require('C:\\ws\\agent\\libs\\agavi\\core\\AgaviContext.class.php');
require('C:\\ws\\agent\\libs\\agavi\\controller\\AgaviController.class.php');
require('C:\\ws\\agent\\libs\\agavi\\controller\\AgaviExecutionContainer.class.php');
require('C:\\ws\\agent\\libs\\agavi\\controller\\AgaviOutputType.class.php');
require('C:\\ws\\agent\\libs\\agavi\\filter\\AgaviIFilter.interface.php');
require('C:\\ws\\agent\\libs\\agavi\\filter\\AgaviIGlobalFilter.interface.php');
require('C:\\ws\\agent\\libs\\agavi\\filter\\AgaviIActionFilter.interface.php');
require('C:\\ws\\agent\\libs\\agavi\\filter\\AgaviFilter.class.php');
require('C:\\ws\\agent\\libs\\agavi\\filter\\AgaviDispatchFilter.class.php');
require('C:\\ws\\agent\\libs\\agavi\\filter\\AgaviExecutionFilter.class.php');
require('C:\\ws\\agent\\libs\\agavi\\filter\\AgaviFilterChain.class.php');
require('C:\\ws\\agent\\libs\\agavi\\renderer\\AgaviRenderer.class.php');
require('C:\\ws\\agent\\libs\\agavi\\request\\AgaviIParametersRequestDataHolder.interface.php');
require('C:\\ws\\agent\\libs\\agavi\\request\\AgaviRequestDataHolder.class.php');
require('C:\\ws\\agent\\libs\\agavi\\request\\AgaviRequest.class.php');
require('C:\\ws\\agent\\libs\\agavi\\response\\AgaviResponse.class.php');
require('C:\\ws\\agent\\libs\\agavi\\routing\\AgaviRouting.class.php');
require('C:\\ws\\agent\\libs\\agavi\\storage\\AgaviStorage.class.php');
require('C:\\ws\\agent\\libs\\agavi\\user\\AgaviUser.class.php');
require('C:\\ws\\agent\\libs\\agavi\\view\\AgaviTemplateLayer.class.php');
require('C:\\ws\\agent\\libs\\agavi\\view\\AgaviView.class.php');

?>