<?php

// This is a compiled Agavi configuration file
// Compiled from: C:/ws/tabeshtour/app/modules/Default/config/config_handlers.xml
// Generated by: AgaviConfigHandlersConfigHandler
// Date: 2007-01-01T12:53:14+0000

return array (
)

?>