<?php

// This is a compiled Agavi configuration file
// Compiled from: C:/ws/agent/app/modules/Admin/config/config_handlers.xml
// Generated by: AgaviConfigHandlersConfigHandler
// Date: 2013-06-26T22:08:40+0000

return array (
)

?>