<?php

// This is a compiled Agavi configuration file
// Compiled from: C:/ws/tabeshtour/app/modules/Admin/config/config_handlers.xml
// Generated by: AgaviConfigHandlersConfigHandler
// Date: 2013-07-13T03:16:48+0000

return array (
)

?>