<?php

// This is a compiled Agavi configuration file
// Compiled from: C:/ws/tabeshtour/app/modules/Admin/config/config_handlers.xml
// Generated by: AgaviConfigHandlersConfigHandler
// Date: 2007-01-01T10:09:39+0000

return array (
)

?>