<?php

// This is a compiled Agavi configuration file
// Compiled from: C:/ws/tabeshtour/app/modules/Default/config/config_handlers.xml
// Generated by: AgaviConfigHandlersConfigHandler
// Date: 2013-06-27T00:36:09+0000

return array (
)

?>