<?php

// This is a compiled Agavi configuration file
// Compiled from: C:/ws/tabeshtour/app/modules/Widgets/config/config_handlers.xml
// Generated by: AgaviConfigHandlersConfigHandler
// Date: 2013-06-27T02:13:28+0000

return array (
)

?>