<?php

// This is a compiled Agavi configuration file
// Compiled from: C:/ws/tabeshtour/app/modules/Admin/config/config_handlers.xml
// Generated by: AgaviConfigHandlersConfigHandler
// Date: 2013-06-30T09:14:21+0000

return array (
)

?>