<?php

// This is a compiled Agavi configuration file
// Compiled from: C:/ws/tabeshtour/app/modules/Admin/validate/Post/Admin/Index.xml
// Generated by: AgaviValidatorConfigHandler
// Date: 2013-06-27T18:02:22+0000

if($method == 'read') {
${'_validator_51cc7e2e784252.90543896'} = new AgaviNumberValidator();
${'_validator_51cc7e2e784252.90543896'}->initialize($this->getContext(), array (
  'type' => 'int',
  'severity' => 'error',
  'required' => true,
  'class' => 'number',
  'name' => '51cc7e2e784252.90543896',
  'base' => NULL,
), array (
  0 => 'id',
), array (
));
${'validationManager'}->addChild(${'_validator_51cc7e2e784252.90543896'});
}

?>