<?php

// This is a compiled Agavi configuration file
// Compiled from: C:/ws/tabeshtour/app/modules/Admin/validate/Post/Admin/Index.xml
// Generated by: AgaviValidatorConfigHandler
// Date: 2013-06-27T19:12:45+0000

if($method == 'read') {
${'_validator_51cc8ead0f91d8.64873177'} = new AgaviNumberValidator();
${'_validator_51cc8ead0f91d8.64873177'}->initialize($this->getContext(), array (
  'type' => 'int',
  'severity' => 'error',
  'required' => true,
  'class' => 'number',
  'name' => '51cc8ead0f91d8.64873177',
  'base' => NULL,
), array (
  0 => 'id',
), array (
));
${'validationManager'}->addChild(${'_validator_51cc8ead0f91d8.64873177'});
}

?>