<?php
// This file generated by Propel 1.6.7 convert-conf target
// from XML runtime conf file C:\ws\agent\dev\db\runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'travel' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'dsn' => 'mysql:host=localhost;dbname=travel',
        'user' => 'root',
        'password' => '',
      ),
    ),
    'default' => 'travel',
  ),
  'generator_version' => '1.6.7',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap-agent-conf.php');
return $conf;